name: ScreenPlugin
version: '${project.version}'
main: com.github.mangoperson.screenplugin.ScreenPlugin
api-version: 1.19
authors: [ MangoPerson ]
description: Display Screen in Minecraft
website: https://github.com/mangoperson
commands:
  screen:
    description: Update the screen
    usage: "Usage: /screen <width> <height> [--w <world>] [--l <x> <y> <z>]"
  mworld:
    description: Use MWorld commands
    usage: Use /mworld help for help
  mwcreate:
    description: Create a world with MWorld
    usage: "Usage: /mwcreate <name> [--t <worldtype: normal|flat|amplififed|large_biomes>] [--s <seed>]"
  mwtp:
    description: Teleport to a world with MWorld
    usage: "Usage: /mwtp <world> <x> <y> <z>"
  mwlist:
    description: List all worlds
    usage: "Usage: /mwlist"
  mwremove:
    description: Delete a world
    usage: "Usage: /mwremove <world>"
  mwhelp:
    description: Get help about MWorld commands
    usage: "Usage: /mwhelp"
